---
- name: Starting MySQL server ...
  service:
    name: mysqld
    state: started
      
- name: Getting temporary password ...
  shell: grep 'temporary password' /var/log/mysqld.log | cut -d' ' -f11
  register: pass
   
- debug: msg="{{pass.stdout}}"
  
- name: Setting root user password ...
  expect:
    command: mysqladmin -u root -p password
    responses: 
      (?i)password: "{{pass.stdout}}"
      New password: "{{root_pass}}"
      Confirm new password: "{{root_pass}}"
  ignore_errors: true
  notify: Restart mysql
  tags:
    - set_root
  
- name: Creation of new database  ...
  mysql_db:
    name:  "{{db_name}}"
    state: present
    login_user: root
    login_password: "{{root_pass}}"
     

         
      
- name: Creation of new user  ...
  mysql_user:
    name: "{{user_name}}"
    password: "{{user_pass}}"
    login_user: root
    login_password: "{{root_pass}}"
    priv: '*.*:ALL,GRANT'
    host: "%"
    state: present


- copy:
    src: dump.sql
    dest: /home/centos/dump.sql
    owner: centos
    group: centos
    mode: 0644
    
- name: dump base ...
  shell: mysql -p{{root_pass}} {{db_name}}  < dump.sql
