---
- name: install tomcat
  yum:
    name: tomcat
    state: installed

- name: start tomcat
  service:
    name: tomcat
    state: started
    enabled: true

- name: install tomcat-webapps
  yum:
    name: tomcat-webapps
    state: installed

- name: install tomcat-admin-webapps
  yum:
    name: tomcat-admin-webapps
    state: installed

- name: )))
  selinux:
    state: disabled

