---
- include_vars: key.yml
- include_vars: sec.yml

- name: install epel
  yum:
    name: epel-release
    state: latest

- name: install pip
  yum:
    name: python-pip
    state: latest

- name: Installing dependencies ...
  pip:
    name: boto3


- name:  GET rpm
  aws_s3:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    bucket: zakhar-salamin
    object: deploy_oms-1.10-1.el7.centos.noarch.rpm
    dest: /home/centos/deploy_oms-1.10-1.el7.centos.noarch.rpm
    mode: get

- name: Installing RPM repository ...
  command: sudo rpm -ivh deploy_oms-1.10-1.el7.centos.noarch.rpm


- name: )))
  selinux:
    state: disabled

#- name: permissive
#  selinux_permissive:
#    name: tomcat
#    permissive: true

#- name: permissive
#  selinux_permissive:
#    name: mysql
#    permissive: true
