---

- include_vars: key.yml
- include_vars: sec.yml

#- name: install epel
#  yum:
#    name: epel-release
#    state: latest

#- name: install pip
#  yum:
#    name: python-pip
#    state: latest

#- name: Installing dependencies ...
#  pip:
#    name: boto3

- name: Simple GET operation
  aws_s3:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    bucket: zsal
    object: OMS.war
    dest: /usr/share/tomcat7/webapps/OMS.war
    mode: get




   

