---

- include_vars: key.yml
- include_vars: sec.yml


- name:  GET war file
  aws_s3:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    bucket: zsal
    object: OMS.war
    dest: /usr/share/tomcat7/webapps/OMS.war
    mode: get




   

