---
- name: install epel
  yum:
    name: epel-release
    state: latest

- name: install pip
  yum:
    name: python-pip
    state: latest

- name: Installing dependencies ...
  pip:
    name: boto3

- name: Simple GET operation
  aws_s3:
    bucket: zakhar-salamin
    object: OMS.war
    dest: /usr/share/tomcat/webapps/OMS.war
    mode: get




   

